version: '3.9'
services:
  auth-server:
    build:
      context: ./servers/auth
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  resource-server:
    build:
      context: ./servers/resource
    ports:
      - "8082:8082"
    depends_on:
      - auth-server
    networks:
      - mynetwork

  client-server:
    build:
      context: ./servers/client
    ports:
      - "8081:8081"
    depends_on:
      - resource-server
    networks:
      - mynetwork

networks:
  mynetwork:
